Лабораторная работа №1. 6312 Никифорова Дарья. 12 вариант.
itsecd/dotnet-2023 pull request #10
Opened 2023-03-04 19:51 UTC by 4u-daisy

Добрый вечер, проверьте пожалуйста, @alxmcs.

Небольшая ремарка касательно л/р: я реализовала связь с базой данных для хранения автоматически сгенерированных данных. Консольное приложение - реализован класс автоматической генерации данных, и также оно было нужно для заполнения бд.

2023-03-07 11:25 UTC, alxmcs requested changes
В целом, код достаточно качественный. Хотя местами в нем творится ![image](https://user-images.githubusercontent.com/70561974/223403395-ab10d08d-6fa4-416a-a291-85da86a89b81.png).

2023-03-07 11:25 UTC, alxmcs commented on dotnet-2023.TestConsoleApp/DataFiles/5Вузов.txt
> +var faclts = new int[] { 1, 3, 4};
У меня сложилось впечатление, что этот файл тут не очень нужен или содержит совсем не то, что нужно

2023-03-07 11:25 UTC, alxmcs commented on dotnet-2023.TestConsoleApp/Generator.cs
> +        var elem = lines[inst].Split('\t');
Опционально:
Есть такое обширное количество форматов сериализации, но тут сплитится содержимое txt файла. :С

2023-03-07 11:25 UTC, alxmcs commented on dotnet-2023.lib/dotnet-2023.DataModel/InstituteDocumentation/InstituteSpeciality.cs
> +﻿using dotnet_2023.DataModel.Organization;
Наименование неймспейса нарушает [гайдлайны](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines) (этот неймспейс и аналогичные  ему - должно быть без андерскоров и c PascalCase).

2023-03-07 11:25 UTC, alxmcs commented on dotnet-2023.lib/dotnet-2023.lib.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "dotnet-2023.DataModel", "dotnet-2023.DataModel\dotnet-2023.DataModel.csproj", "{4FB45543-667C-4C67-9B6D-5483DC2CEE07}"
Проекты  и солюшен я бы тоже попереименовывал, чтобы был PascalCase.

2023-03-07 17:14 UTC, 4u-daisy commented
Замечания исправлены.

2023-03-07 17:22 UTC, 4u-daisy commented
@alxmcs, замечания исправлены

2023-03-07 17:24 UTC, alxmcs commented
В таком случае ![image](https://user-images.githubusercontent.com/70561974/223500284-ad7a178f-6b24-405d-bd2c-c5d7523df500.png)

2023-03-08 05:26 UTC, alxmcs approved these changes

2023-03-13 07:58 UTC, closed without merging