Лабораторная работа №2, варинат №10. Куликов А.С., 6312-100503D
itsecd/dotnet-2023 pull request #106
Opened 2023-05-16 12:20 UTC by HackerA777

Созданы контроллеры, репозитории и "DTO"для  Product, StorageCell, Invoice. 
Прошу вас проверить, @alxmcs

2023-05-17 11:24 UTC, alxmcs requested changes
Общие замечания (чтобы не писать кучу комментариев в коде):
1) нет xml-комментариев непосредственно к классам dto (к их пропертям есть),
2) нет xml-комментариев к методам контроллеров,
3) отсутствует контроллер с аналитикой,
4) можно было обойтись единственным репозиторием с несколькими коллекциями вместо нескольких репозиториев с единственной коллекцией внутри,
5) надо запустить code cleanup по солюшену,
6) dto классы содержат полный набор пропертей dao классов, хотя часть dto пропертей в коде не используется; соответственно, их можно убрать,
7) че так долго лабу делал?

2023-05-18 09:17 UTC, HackerA777 commented
1. Добавил xml-комментарии к классам Dto и к методам контроллеров.
2. Создал контроллер с аналитикой
3. Все репозитории переместил в один с несколькими коллекциями
4. Создал новые Dto для запросов по заданию. В InvoicePostDto нужно убрать Id, но пока этого не сделал, потому что нет привязки к БД
5. Clean up по солюшену сделал. Если вы увидете, что clean up не сделался, то буду просить вас  о том, чтобы вы мне объяснили как это делать правильно. 
6. Извините, виноват (ответ на ваш 7-ой комментарий)

2023-05-20 09:20 UTC, alxmcs requested changes

2023-05-20 09:20 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseWarehouseServer/Controllers/AnalyticsController.cs
> +                     where invoice.ShipmentDate == new DateTime(2023, 2, 11)
Дата захардкожена, а должна быть параметром метода контроллера

2023-05-20 09:20 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseWarehouseServer/Controllers/AnalyticsController.cs
> +                     where invoice.ShipmentDate > new DateTime(2023, 2, 1) && invoice.ShipmentDate < new DateTime(2023, 2, 15)
Даты захардкожены, а должны быть параметрами метода контроллера

2023-05-20 09:40 UTC, HackerA777 commented
Исправил

2023-05-20 09:46 UTC, alxmcs approved these changes

2023-05-23 08:37 UTC, alxmcs commented
Если 3 лабораторная готова, то переименовывай пул-риквест и запрашивай ревью

2023-05-23 08:42 UTC, HackerA777 commented
Мне осталось проверить контроллеры и почистить код. Ревью запрошу в районе
17:00

Вт, 23 мая 2023 г. в 12:37 PM, alxmcs ***@***.***>:

> Если 3 лабораторная готова, то переименовывай пул-риквест и запрашивай
> ревью
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/itsecd/dotnet-2023/pull/106#issuecomment-1558810296>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVSQCKYZRGM7IC25CLBVGOTXHRZL7ANCNFSM6AAAAAAYDSAPGQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-05-23 13:55 UTC, HackerA777 commented
1. Перестроены модели
2. Переписаны контроллеры под Entity Framework Core 
3. Добавлены тестовые данные в dbContext

2023-05-23 14:12 UTC, alxmcs requested changes

2023-05-23 14:12 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseData/Invoice.cs
> +    [Column("invoiceId")]
camelСase - не самый удобный  регистр для именования сущностей в бд, я бы предложил использовать snake_case
(тут и далее по коду)

2023-05-23 14:12 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseData/Invoice.cs
> +[Table("Invoices")]
Тем более, что таблицы почему то при этом называются PascalCase

2023-05-23 14:12 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseData/InvoiceContent.cs
> +    ///
Какое-то
<br/>
<br/>
<br/>
<br/>
<br/>
высокое саммари

2023-05-23 14:12 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseWarehouseServer/Controllers/InvoiceController.cs
> +    public async Task<ActionResult<Invoice>> Post([FromBody] InvoicePostDto invoice)
Почему возвращается не dto, а dao?
Если что-то так хочется все-таки вернуть на post, то я бы предложил возвращать id добавленной записи

2023-05-23 14:12 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseWarehouseServer/Controllers/ProductController.cs
> +    public async Task<ActionResult<Product>> Post([FromBody] ProductPostDto product)
Аналогично

2023-05-23 14:12 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseWarehouseServer/Controllers/StorageCellController.cs
> +    public async Task<ActionResult<StorageCell>> Post([FromBody] StorageCellPostDto storageCell)
Аналогично

2023-05-23 14:12 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseWarehouseServer/MappingProfile.cs
> +        CreateMap<Product, ProductGetDto>().ReverseMap();
ReverseMap() тебе не нужен - у тебя отдельные dto на get и на post - они мапятся только в одном направлении
(здесь и далее по коду)

2023-05-23 14:12 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseWarehouseServer/Repositories/MainRepository.cs
> +public class MainRepository : IMainRepository
Этот класс и интерфейс, который он имплементирует, тебе больше не нужны, так что их можно удалять

2023-05-30 06:56 UTC, alxmcs approved these changes

2023-05-31 09:08 UTC, closed without merging