Скобцов Владимир 6312 - Лабораторная работа №4 Вариант 14
itsecd/dotnet-2023 pull request #109
Opened 2023-05-18 21:46 UTC by Sv163Sam

2023-05-23 10:06 UTC, alxmcs requested changes
Общие замечания:

1) Не наблюдаю вью для данных, которые предоставляет контроллер аналитики.
2) Убрать из репозитория служебные файлы среды разработки.
3) В проект включены директории, которые не добавлены в гит.

2023-05-25 12:30 UTC, Sv163Sam commented
Здравствуйте, можете пожалуйста пояснить по первому замечанию.

2023-05-30 07:24 UTC, alxmcs requested changes

2023-05-30 07:24 UTC, alxmcs commented on TaxiDepo.Client/.gitignore
>  [Rr]eleases/
Зачем .gitignore переехал из рута в клиентский проект?

2023-05-30 07:24 UTC, alxmcs commented on TaxiDepo.Model/Car.cs
> +    [Column("Id")]
Проглядел на ревью 3 лабы - если таблицы у тебя названы снейк кейсом, то и столбцы стоит именовать также снейк кейсом

2023-05-30 08:44 UTC, alxmcs requested changes
Забыл кое о чем - по правилам сдачи в ридми репозитория должны быть скрины софта

2023-05-30 08:51 UTC, Sv163Sam commented
C сервером или просто клиента?

2023-05-30 08:53 UTC, alxmcs commented
Только клиента

2023-05-31 09:08 UTC, closed without merging