Лабораторная работа №3 - Тарасова А. П. гр. 6311 вариант 22
itsecd/dotnet-2023 pull request #111
Opened 2023-05-19 14:26 UTC by DimNice

2023-05-19 14:31 UTC, DimNice commented
![image](https://github.com/itsecd/dotnet-2023/assets/93138173/abe6914e-5c0f-4525-9ad5-1350ae8638da)
![image](https://github.com/itsecd/dotnet-2023/assets/93138173/e076fb23-b8cb-4e0c-87cf-68177b2859b4)
Николай Викторович, здравствуйте. Сделала как вы мне сказали, всё заработало (вроде). Начала делать дальше, добавила полёты, но что-то пошло не так, хотя делала всё по аналогии. Вылетают два исключения, то одно, то другое. (фото) Не понимаю что не так, подскажите пожалуйста

2023-05-20 10:26 UTC, kolyanch requested changes

2023-05-20 10:26 UTC, kolyanch commented on AirplaneBookingSystem/AirplaneBookingSystem.Client/ViewModels/FlightViewModel.cs
> +using System.ComponentModel.DataAnnotations.Schema;
Сделать cleanup

2023-05-20 10:26 UTC, kolyanch commented on AirplaneBookingSystem/AirplaneBookingSystem.Client/ViewModels/MainWindowViewModel.cs
> +    }
Объединить данные методы в один. Скорей всего это решит проблемы

2023-05-20 10:26 UTC, kolyanch commented on AirplaneBookingSystem/BlowFish/BlowFish.sln
Файлы данные видимо относятся к какому-то другому курсу

2023-05-20 12:26 UTC, DimNice commented
Исправила, но всё ещё не работает..

2023-05-20 13:25 UTC, kolyanch commented
1. Проверьте есть ли маппинг для AirplaneViewModel (его нет сейчас)
2. DateTime сменить на DateTimeOffset в этом классе

2023-05-22 04:42 UTC, kolyanch approved these changes

2023-05-24 11:46 UTC, closed without merging