Лабораторные работы №1-3, вариант 23. Телегина Мария 6311
itsecd/dotnet-2023 pull request #121
Opened 2023-05-29 02:11 UTC by T-Marria

Выполнены факультативные задания: GitHub Actions и использование СУБД PostgreSQL

2023-05-29 05:53 UTC, kolyanch requested changes

2023-05-29 05:53 UTC, kolyanch commented on Department/Department.Server/Controllers/AnalyticsController.cs
> +    private readonly IMapper _mapper;
Маппер точно нужен?

2023-05-29 05:53 UTC, kolyanch commented on Department/Department.Server/Controllers/AnalyticsController.cs
> +namespace BikeRental.Server.Controllers;
Очень странный namespace

2023-05-29 05:53 UTC, kolyanch commented on Department/Department.Server/Controllers/AnalyticsController.cs
> +        if (_context.Courses == null || _context.Teachers == null)
Согласно аннотациям данных свойств они никогда не равны null. Данная проверка бессмысленна. Тут и в других методах всех контроллеров

2023-05-29 05:53 UTC, kolyanch commented on Department/Department.Server/Controllers/AnalyticsController.cs
> +     select teacher).ToListAsync();
Выровнять код

2023-05-29 11:48 UTC, kolyanch requested changes

2023-05-29 11:48 UTC, kolyanch commented on Department/Department.Server/Controllers/AnalyticsController.cs
> +    public AnalyticsController(DepartmentDbContext context, IMapper mapper, ILogger<AnalyticsController> logger)
Зачем нужна зависимость на mapper?

2023-05-29 11:48 UTC, kolyanch commented on Department/Department.Server/Controllers/CoursesController.cs
> +        if (_context.Courses == null)
Во всех методах **всех** контроллеров свойства не null, исходя из дизайна

2023-05-30 06:14 UTC, kolyanch approved these changes

2023-05-31 19:55 UTC, T-Marria commented
Доделана 4-я лабораторная работа с выводом всех таблиц.

2023-06-03 12:59 UTC, kolyanch requested changes

2023-06-03 12:59 UTC, kolyanch commented on Department/Department.Server/Program.cs
> +    options.UseMySQL(builder.Configuration.GetConnectionString("MySQL")!)
Какая СУБД по итогу используется?

2023-06-03 14:11 UTC, T-Marria commented on Department/Department.Server/Program.cs
> +    options.UseMySQL(builder.Configuration.GetConnectionString("MySQL")!)
Я меняла с одной на другую, сейчас в итоге используется MySQL.
Оставила в коде закомментированные строки, чтобы быстро переключаться на postgre.

2023-06-04 09:01 UTC, kolyanch approved these changes

2023-06-04 10:00 UTC, T-Marria commented on Department/Department.Server/Program.cs
> +    options.UseMySQL(builder.Configuration.GetConnectionString("MySQL")!)
Для тестирования подключала MySQL, сейчас вернула postrge

2023-06-06 16:17 UTC, closed without merging