Лабораторная работа №4, вариант №10. Куликов А.С., 6312-100503D
itsecd/dotnet-2023 pull request #134
Opened 2023-06-02 08:37 UTC by HackerA777

2023-06-04 10:50 UTC, HackerA777 commented
Реализована клиентская часть проекта.
Прошу вас проверить, @alxmcs

2023-06-05 09:02 UTC, alxmcs requested changes
Видимо, я проглядел в предыдущих ревью, но есть проблема с наименованиями проектов и неймспейсов.
Должно быть:
`EnterpriseWarehouse.Model`
`EnterpriseWarehouse.Tests`
`EnterpriseWarehouse.Server`
`EnterpriseWarehouse.Client`

2023-06-05 15:37 UTC, alxmcs requested changes

2023-06-05 15:37 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseWarehouse.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Enterprise.Data.Tests", "EnterpriseTests\Enterprise.Data.Tests.csproj", "{DF7E849E-335F-427C-8F2D-6AFBA2F89F2C}"
Проекты переменованы, а физические фолдеры - нет

2023-06-05 15:37 UTC, alxmcs commented on EnterpriseWarehouse/EnterpriseWarehouse.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Enterprise.Data", "EnterpriseData\Enterprise.Data.csproj", "{603E637C-4773-4F7C-A5DE-7DD0DCA65802}"
Мы же вроде договорились, что это будет Model

2023-06-05 16:22 UTC, HackerA777 commented on EnterpriseWarehouse/EnterpriseWarehouse.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Enterprise.Data.Tests", "EnterpriseTests\Enterprise.Data.Tests.csproj", "{DF7E849E-335F-427C-8F2D-6AFBA2F89F2C}"
Тяжеловато мне это сейчас далось...

2023-06-06 08:44 UTC, alxmcs approved these changes

2023-06-14 08:13 UTC, closed without merging