Авиакомпания
itsecd/dotnet-2023 pull request #20
Opened 2023-03-10 20:58 UTC by Smoker63

Осталось дописать тесты к запросам

2023-03-13 08:09 UTC, alxmcs requested changes

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Flight.cs
> +    public string Departure_place { get; set; } = string.Empty;
Нарушение [соглашений ](https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md)об именовании объектов

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Flight.cs
> +    public DateTime? Departure_date { get; set; }
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Airplane.cs
> +    public int Load_Capacity { get; set; } = 0;
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Flight.cs
> +    public DateTime? Arrival_date { get; set; }
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Flight.cs
> +    public TimeSpan Flight_time { get; set; }
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Passenger.cs
> +    public int Passport_number { get; set; } = 0;
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Passenger.cs
> +    public Passenger(int passport_number, string name)
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Passenger.cs
> +    public Passenger(int passport_number, string name, List<Ticket> tickets)
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Passenger.cs
> +    public void Add_ticket(Ticket ticket)
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Passenger.cs
> +    public void Add_ticket(List<Ticket> tickets)
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Flight.cs
> +    public Flight(string cipher, string departure_place, string destination, DateTime? departure_date, DateTime arrival_date, Airplane airplane, List<Ticket> tickets)
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Airline.cs
> +    public void Add_to_passenger_list(Passenger passenger)
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Airline.cs
> +    public void Add_to_flight_list(Flight flight)
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Airline.cs
> +    public void Add_to_airplane_list(Airplane airplane)
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Ticket.cs
> +    public double Baggage_weight { get; set; } = 0;
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Domain/Ticket.cs
> +    public string Seat_number { get; set; } = string.Empty;
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    private List<Flight> Default_flights()
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    private List<Passenger> Default_passengers()
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Airplane_test()
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Airplane_constructor_test()
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Ticket_constructor_test()
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Flight_constructor_test()
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Passenger_constructor_test()
Аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Task1()
Лучше назвать метод репрезентативным именем, которое отражало бы, что в нем происходит, а факт того, что он выполняет задачу номер 1 из условия лабораторной отметить в саммари

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Task2()
Тут аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Task3()
Тут аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Task4()
Тут аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Task5()
Тут аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.Test/AirlineTest.cs
> +    public void Task6()
Тут аналогично

2023-03-13 08:09 UTC, alxmcs commented on AirlineClasses/AirlineClasses.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "AirlineClasses", "AirlineClasses.Domain\AirlineClasses.csproj", "{4E72C214-C5D4-4B0F-BC6B-0C0268D85FBF}"
`AirlineClasses` звучит подходящим именем для класслибы, но не для решения  и не в качестве глобального неймспейса для всего кода проекта

2023-03-13 09:00 UTC, Smoker63 commented on AirlineClasses/AirlineClasses.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "AirlineClasses", "AirlineClasses.Domain\AirlineClasses.csproj", "{4E72C214-C5D4-4B0F-BC6B-0C0268D85FBF}"
исправил

2023-03-13 09:01 UTC, Smoker63 commented
исправлено

2023-03-13 09:29 UTC, alxmcs approved these changes

2023-04-12 04:59 UTC, alxmcs commented
Ну и зачем ты это сделал?
Пул-риквест закрывается преподавателем после того, как сдана теория.

2023-04-12 06:43 UTC, Smoker63 commented
То есть я не могу сдать код по второй работе на ревью без сданной теории по первой работе?
Я могу назад открыть закрытый пулл-риквест?

2023-04-12 07:02 UTC, alxmcs commented
Половина семестра прошла, а ты тупишь.

Ты можешь сдавать код вне зависимости от теории.
Просто продолжаешь коммитить в этот же пул-риквест и указываешь в описании pr, что тут несколько лаб одновременно.
Пул-риквест закрывается тогда, когда вся теория сдана. Когда принят код - ему ставится тег `approved`.

В репозитории 46 пул-риквестов закрытых, 23 открытых - примеров, чтобы посмотреть, как это можно сделать, полно.

2023-04-12 08:46 UTC, alxmcs requested changes

2023-04-12 08:46 UTC, alxmcs commented on Airline/Airline.Server/Controllers/AnalyticsController.cs
> +    [HttpGet("passengers-without-baggage")]
![image](https://user-images.githubusercontent.com/70561974/231401335-ed58b3e8-2a07-4002-873c-d20afd08aac8.png)
Текст задания предполагает наличие параметра для запроса - номер рейса

2023-04-12 08:46 UTC, alxmcs commented on Airline/Airline.Server/MappingProfile.cs
> +        CreateMap<Passenger, PassengerPostDto>();
Этот маппинг не нужен

2023-04-12 08:46 UTC, alxmcs commented on Airline/Airline.Server/MappingProfile.cs
> +        CreateMap<Flight, FlightPostDto>();
Аналогично

2023-04-12 08:46 UTC, alxmcs commented on Airline/Airline.Server/MappingProfile.cs
> +        CreateMap<Ticket, TicketPostDto>();
Отсутствует `TicketGetDto`, раз есть разделение Dto по типу запроса для всех остальных классов?

2023-04-12 08:46 UTC, alxmcs commented on Airline/Airline.Server/MappingProfile.cs
> +        CreateMap<Airplane, AirplanePostDto>();
Этот маппинг тоже бесполезен

2023-04-12 10:35 UTC, alxmcs requested changes

2023-04-12 10:35 UTC, alxmcs commented on Airline/Airline.Server/Controllers/AnalyticsController.cs
> +                       where (flight.Airplane.Equals(plane)) &&
Здесь логичнее искать `flight.Airplane.Model`, совпадающий с `airplaneType`

2023-04-12 10:35 UTC, alxmcs commented on Airline/Airline.Server/Controllers/AnalyticsController.cs
> +    public IEnumerable<int> GetFlightsWithMaxCountOfPassengers()
Хотя бы название рейса селектни, а то это совсем уныло:
![image](https://user-images.githubusercontent.com/70561974/231431937-a33359b9-8cd1-4f76-852f-de5ee39d6065.png)

2023-04-12 10:35 UTC, alxmcs commented on Airline/Airline.Server/Controllers/AnalyticsController.cs
> +    public IEnumerable<double> GetMaxAndAvgBaggageAmountFromSpecifiedSource(string source)
Догадаться, что из этого max, а что из этого avg, конечно, труда не составляет, но вот если бы это был не список, а жсон-объект с соответствующими полями, было бы лучше
![image](https://user-images.githubusercontent.com/70561974/231432307-6852a06c-f0dc-4e7b-a881-f436c7a6ec8e.png)

2023-04-12 11:06 UTC, alxmcs approved these changes

2023-04-19 09:43 UTC, closed without merging