Лабораторная работа №1 - Тарасова А. П. гр. 6311 вариант 22
itsecd/dotnet-2023 pull request #23
Opened 2023-03-13 05:05 UTC by DimNice

2023-03-13 05:53 UTC, kolyanch requested changes

2023-03-13 05:53 UTC, kolyanch commented on AirplaneBookingSystem.Domain/AirplaneBookingSystem.Domain/Client.cs
> +    public DateOnly BirthdayData { get; set; } = new DateOnly();
Тип лучше заменить на DateTime. Так будет меньше проблем в дальнейшем. В других классах аналогично

2023-03-13 05:53 UTC, kolyanch commented on AirplaneBookingSystem.Domain/AirplaneBookingSystem.Domain/Ticket.cs
> +public class Ticket
Добавить идентификаторы клиента и полета/рейса

2023-03-13 05:53 UTC, kolyanch commented on AirplaneBookingSystem.Domain/AirplaneBookingSystem.Tests/AirlineBookingSystemTests.cs
> +        var request = ((from flight in _fixture.FixtureFlights
1. Лишние скобки
2. Использовать свойство Count, а не метод

2023-03-13 19:04 UTC, DimNice commented
Здравствуйте, у меня вопрос по поводу реализации идентификаторов. Идентификаторы это поле класса или что-то другое? подскажите пожалуйста

2023-03-13 19:06 UTC, kolyanch commented
> Здравствуйте, у меня вопрос по поводу реализации идентификаторов. Идентификаторы это поле класса или что-то другое? подскажите пожалуйста

Свойства класса. Ссылки на клиента и рейс

2023-03-14 08:26 UTC, kolyanch commented on AirplaneBookingSystem.Domain/AirplaneBookingSystem.Tests/AirlineBookingSystemTests.cs
> +        var request = (from client in _fixture.FixtureClient
Запрос должен содержать группировку. Примерно так:
```C#
var request = (
            from client in _fixture.FixtureClient
            from ticket in client.Tickets
            group ticket by ticket.Flight into flight
            orderby flight.Key.Tickets.Count descending 
            select new
            {
                flight.Key.DepartureCity,
                flight.Key.ArrivalCity,
                flight.Key.Tickets
            }
            ).Take(5).ToList();
```

Но у вас сейчас не хватает связей в тестовом наборе данных (Fixture)

2023-03-14 11:11 UTC, kolyanch requested changes

2023-03-14 11:11 UTC, kolyanch commented on AirplaneBookingSystem.Domain/AirplaneBookingSystem.Tests/AirlineBookingSystemTests.cs
> +                          orderby flight.Key.Tickets.Count() descending
Тут и ниже свойство Count, а не метод

2023-03-14 11:42 UTC, kolyanch approved these changes

2023-03-15 12:22 UTC, closed without merging