LR №1, Gudzenko Igor Nicolaevich, group №6312
itsecd/dotnet-2023 pull request #24
Opened 2023-03-13 08:20 UTC by gudzen2517

2023-03-13 08:28 UTC, gudzen2517 commented
.

2023-03-14 07:07 UTC, alxmcs requested changes
Общие замечания: 
* прогнать code cleanup по солюшену
* вменяемым образом именовать будущие коммиты

2023-03-14 07:07 UTC, alxmcs commented on service_of_transport_managment/Unit.Tests/UnitTest.cs
> +        [Fact]
Отступ. Code cleanup вообще запускался по решению?

2023-03-14 07:07 UTC, alxmcs commented on service_of_transport_managment/Unit.Tests/UnitTest.cs
> +    public void Task2()
Аналогично замечанию к `Task1`

2023-03-14 07:07 UTC, alxmcs commented on service_of_transport_managment/Unit.Tests/UnitTest.cs
> +    public void Task3()
Аналогично замечанию к `Task1`

2023-03-14 07:07 UTC, alxmcs commented on service_of_transport_managment/Unit.Tests/UnitTest.cs
> +    /// </summary>
Почему саммари под атрибутом?

2023-03-14 07:07 UTC, alxmcs commented on service_of_transport_managment/Unit.Tests/UnitTest.cs
> +    public void Task4()
Аналогично замечанию к `Task1`

2023-03-14 07:07 UTC, alxmcs commented on service_of_transport_managment/Unit.Tests/UnitTest.cs
> +    public void Task5()
Аналогично замечанию к `Task1`

2023-03-14 07:07 UTC, alxmcs commented on service_of_transport_managment/TransManagment/TransManagment.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "TransManagment", "TransManagment.csproj", "{E1BC7AEB-1053-440C-9DB3-8B6EC30FA1B7}"
Название солюшена нарушает naming conventions
Название класс либы никак не намекает, что в ней содержится
Название проекта с юнит-тестами - мое почтение, намекает, что в нем юнит тесты. только никак не сигнализирует, что именно там тестируется.

Относительно грамотным именованием, по моему мнению, было бы:

<ИмяСолюшенаПаскальКейсом>.sln
<ИмяСолюшенаПаскальКейсом>.<Model/Classes/т.д.>.csproj
<ИмяСолюшенаПаскальКейсом>.<Model/Classes/т.д.>.Tests.csproj

2023-03-14 08:55 UTC, alxmcs requested changes
Или повторное ревью было запрошено слишком рано, или ты проигнорировал больше половины моих замечаний

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Driver.cs
> +    public string First_name { get; set; } = string.Empty;
Аналогично

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Driver.cs
> +    public string Last_name { get; set; } = string.Empty;
Аналогично

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Driver.cs
> +    public int Driver_card { get; set; } = 0;
Аналогично

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Driver.cs
> +    public Driver(int _driver_id, string _first_name, string _last_name, string _patronymic, int _passport, int _driver_card, int _number)
Аналогично

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Route.cs
> +    public DateTime Time_to { get; set; } = new DateTime();
Аналогично

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Route.cs
> +    public DateTime Time_from { get; set; } = new DateTime();
Аналогично

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Route.cs
> +    public Route(int _route_id, DateOnly _date, DateTime _time_to, DateTime _time_from, Transport _transport, Driver _driver)
Аналогично

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Transport.cs
> +    public int Transport_id { get; set; } = 0;
Аналогично

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Transport.cs
> +    public DateOnly Date_make { get; set; } //= new DateOnly();
Аналогично

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Transport.cs
> +    public Transport(int _transport_id, string _type, string _model, DateOnly _date_make)
Аналогично

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Tests/TransportManagmentTests.cs
> +namespace Unit.Tests;
Неймспейс остался прежним

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Driver.cs
> +﻿namespace TransManagment.Domain;
Неймспейс все еще `TransManagment`

Зачем делать неймспейс `.Domain`, хотя проект называется `.Classes`?
Чтобы причинять дискомфорт людям, которые будут смотреть/использовать твой код?

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Tests/TransportManagmentTests.cs
> +public class UnitTest
Класс все еще называется совершенно нерепрезентативно, и его имя не соответствует названию исходника, в котором он лежит.
Думаю то, что в проекте  `.Tests` будут находиться юнит-тесты - достаточно очевидно.

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Tests/TransportManagmentTests.cs
> +    public List<Transport> FixturTrans()
![image](https://user-images.githubusercontent.com/70561974/224947694-fe03864c-5ca4-428a-89b8-1b5e208b5790.png)

Более того, `Fixtur` все еще с опечаткой

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Tests/TransportManagmentTests.cs
> +
Судя по случайному расположению пустых строк кода между методами, code cleanup никто не запускал

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Classes/Route.cs
> +    public int Route_id { get; set; } = 0;
![image](https://user-images.githubusercontent.com/70561974/224946315-1c23fe2a-d5c9-4609-a3fe-f3d4440eb556.png)

2023-03-14 08:55 UTC, alxmcs commented on ServiceOfTransportManagment/TransportManagment.Tests/TransportManagmentTests.cs
> +    public List<Driver> FixtureDriv()
![image](https://user-images.githubusercontent.com/70561974/224947614-ac5f5cfa-45c3-4447-b0db-396caab054d8.png)

2023-03-15 07:35 UTC, alxmcs requested changes
Прекрасно, теперь на код не больно смотреть и можно изучить более детально бизнес-классы приложения и их связи.

В условии задачи сказано, что:
![image](https://user-images.githubusercontent.com/70561974/225236922-6c43343b-c8d5-4dcd-ad1c-5803c9325254.png)

Из чего следует, что:
1) транспортное средство может курсировать по разным маршрутам в разные даты,
2) транспортное средство могут водить разные водители в разные дни,
3) в разные даты водитель может водить разные транспортные средства.
Соответственно, водители и транспортные средства имеют связь многие-ко-многим через маршруты.

Реализацию этой связи в текущем коде я пока что не наблюдаю.

2023-03-15 11:41 UTC, gudzen2517 commented
Я же правильно понял, что из условия следует, что в классах водителей и транспорта должны лежать списки поездок для каждого?

2023-03-22 09:34 UTC, closed without merging