Лабораторная № 1 Снитенко Н. 6311 - 10.05.03D
itsecd/dotnet-2023 pull request #31
Opened 2023-03-15 11:40 UTC by Nadia-Snitenko

по Московскому времени успеваю

2023-03-15 12:57 UTC, kolyanch requested changes
1. Solution и проекты переименовать, чтобы не было пробелов в названии
2. Проект с тестами переименовать и все namespac-ы в нем
3. UnitTest1.cs переименовать
4. Сделать code cleanup, убрать лишние using в коде

В остальном вроде чисто

2023-03-17 05:41 UTC, Nadia-Snitenko commented
Files are renamed

2023-03-17 07:01 UTC, kolyanch requested changes

2023-03-17 07:01 UTC, kolyanch commented on MusicMarketApp/MusicMarketplace.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MusicMarketplace", "Music Marketplace\MusicMarketplace.csproj", "{DC10FC1C-7043-4FDB-B915-F9312A0F2332}"
Поменять ссылки на проекты в данном файле

2023-03-17 07:12 UTC, Nadia-Snitenko reviewed
Change file-ways

2023-03-17 07:14 UTC, Nadia-Snitenko commented on MusicMarketApp/MusicMarketplace.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MusicMarketplace", "Music Marketplace\MusicMarketplace.csproj", "{DC10FC1C-7043-4FDB-B915-F9312A0F2332}"
Ссылки исправлены

2023-03-18 15:42 UTC, kolyanch requested changes

2023-03-18 15:42 UTC, kolyanch commented on MusicMarketApp/MusicMarketTests/MusicMarketTests.cs
> +    /// ������ ������: ������� ���������� � ���� ��������� ��������� ����������.
Проблемы с кодировкой файла

2023-03-18 15:42 UTC, kolyanch commented on MM.md
Этот файл удалить

2023-03-18 15:42 UTC, kolyanch commented on MusicMarketApp/MusicMarketTests/MusicMarketFixture.cs
> +    public List<Ńustomer> FixtureŃustomers
Тут какие-то странные символы

2023-03-20 05:58 UTC, Nadia-Snitenko commented
All changed

2023-03-20 08:15 UTC, kolyanch commented on MusicMarketApp/MusicMarketTests/MusicMarketFixture.cs
> +    public List<Ńustomer> FixtureŃustomers
Все ещё странные символы. В слове Customer используйте латинскую букву C, а не русскую

2023-03-20 08:17 UTC, kolyanch requested changes

2023-03-20 08:17 UTC, kolyanch commented on MusicMarketApp/MusicMarketTests/MusicMarketFixture.cs
> +            var ńustomers = new List<Customer>();
тут

2023-03-20 08:17 UTC, kolyanch commented on MusicMarketApp/MusicMarketTests/MusicMarketFixture.cs
> +    public List<Customer> FixtureCustomers
У вас точно нет ошибок компиляции в этой строке?

2023-03-20 17:53 UTC, Nadia-Snitenko commented
А теперь?

2023-03-22 04:06 UTC, kolyanch commented on MusicMarketApp/MusicMarketTests/MusicMarketTests.cs
> +        var customers = _fixture.FixtureÑustomers.ToList();
Проект по прежнему не билдится. Тут опять какой-то странный символ

2023-03-22 12:42 UTC, kolyanch approved these changes

2023-03-29 10:00 UTC, closed without merging