Dornet-2023
itsecd/dotnet-2023 pull request #33
Opened 2023-03-15 16:39 UTC by Sv163Sam

2023-03-16 07:04 UTC, alxmcs requested changes
Жду нормальное название и описание пул-риквеста

2023-03-17 09:52 UTC, alxmcs requested changes
Общее замечание: где файл с солюшеном?

2023-03-17 09:52 UTC, alxmcs commented on README.md
> +<img width="999" alt="Снимок экрана 2023-03-16 в 13 28 14" src="https://user-images.githubusercontent.com/85555964/225573804-8fcd98d9-8902-440c-87f9-3986849f9d9f.png">
Какие авиарейсы? У тебя же таксопарк

2023-03-17 09:52 UTC, alxmcs commented on README.md
> +<img width="1009" alt="Снимок экрана 2023-03-15 в 20 37 40" src="https://user-images.githubusercontent.com/85555964/225378638-51b43274-7874-40d7-87ec-d7eaf35730df.png">
Ты же в курсе, что из pdf можно просто скопировать текст, а не скринить экран?

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +    /// <param name="number"></param>
Зачем указывать параметры в саммари, если ты все равно их никак не описываешь?

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +    /// <param name="carObj"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +    /// <param name="carObj1"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +    /// <param name="carObj1"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +    /// <param name="obj"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +    /// <returns></returns>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/RideData.cs
> +    /// <param name="departurePlace"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/RideData.cs
> +    /// <param name="obj"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    /// <param name="driverObj"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    /// <param name="driverInfo"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    /// <param name="driverInfo"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    /// <param name="userInfo"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    /// <param name="userInfo"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    /// <param name="driverInfo"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    /// <param name="carInfo"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    /// <param name="userInfo"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    /// <param name="rideInfo"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/UsersData.cs
> +    /// <param name="phoneNumber"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/UsersData.cs
> +    /// <param name="userObj"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/UsersData.cs
> +    /// <param name="userObj1"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/UsersData.cs
> +    /// <param name="userObj1"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/UsersData.cs
> +    /// <param name="obj"></param>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/UsersData.cs
> +    /// <returns></returns>
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    public void TryAddPostToDrivers(Driver driverInfo)
Этот метод нигде в коде не используется

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    public void TryAddPostToCars(Car carInfo)
Этот метод нигде в коде не используется

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    public void TryAddPostToRides(Ride rideInfo)
Этот метод нигде в коде не используется

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +namespace TaxiDepotClass;
Неймспейс и название проекта не соответствуют [соглашениям](https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md) об именовании

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepottests/TaxiDepotTest.cs
> +namespace TaxiDepotTests;
Неймспейс и название проекта не соответствуют [соглашениям](https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md) об именовании

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +public class Car
Имя исходника не соответствует имени класса

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/DriverData.cs
> +public class Driver
Имя исходника не соответствует имени класса

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/RideData.cs
> +public class Ride
Имя исходника не соответствует имени класса

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/UsersData.cs
> +public class User
Имя исходника не соответствует имени класса

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/UsersData.cs
> +public class User
У пассажира отсутствует коллекция совершенных им поездок

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/RideData.cs
> +public class Ride
В классе поездки нет сведений о пассажире

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +public class Car
У машины нет коллекции совершенных ей поездок

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/DriverData.cs
> +public class Driver
У класса водителя нет сведений о закрепленной за ним машине

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +public class Car
У машины нет связи с закрепленным за ней водителем

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    public Dictionary<Driver, Car> CarAssignedToDriver;
Связь между водителями и автомобилями логичнее реализовать в соответствующих классах

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/TaxiDepot.cs
> +    public Dictionary<User, Ride> UserAssignedToRide;
Аналогично - связь между пассажирами и  поездками лучше реализовать в соответствующих классах

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepottests/TaxiDepotTest.cs
> +    /// Task 1
Было бы неплохо описать в саммари в чем task 1 заключается

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepottests/TaxiDepotTest.cs
> +    /// Task 2
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepottests/TaxiDepotTest.cs
> +    /// Task 4
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepottests/TaxiDepotTest.cs
> +    /// Task 5
Аналогично

2023-03-17 09:52 UTC, alxmcs commented on TaxiDepot/TaxiDepotClass/CarData.cs
> +    /// Car color - field
Во первых, это не field
Во-вторых, эта часть комментария через тире мне кажется крайне излишней как тут, так и далее по коду

2023-03-17 09:52 UTC, alxmcs requested changes
Общее замечание: где файл с солюшеном?

2023-03-17 09:54 UTC, alxmcs commented
Я накидал столько придирок, что страница зависла, а ревью задублировалось.
Забавно

2023-03-19 17:02 UTC, Sv163Sam commented
Здравствуйте, по ошибке Merge сделал, как исправить

2023-03-19 17:14 UTC, alxmcs commented
У тебя при пуле с локальной машины автоматически смержились коммиты, сделанные  параллельно им через веб-сайт.
Ничего трагического не произошло.

2023-03-20 07:12 UTC, alxmcs commented
Еслиэто все, тогда ![image](https://user-images.githubusercontent.com/70561974/226270925-5900f260-7ac2-491e-a105-e1f1c4dc1de4.png)

2023-03-20 07:50 UTC, Sv163Sam commented
Еще переделываю тесты

2023-03-21 05:09 UTC, alxmcs approved these changes

2023-03-22 09:33 UTC, closed without merging