ЛР1 Вариант № 16 Матросов Максим 6311-10.05.03D
itsecd/dotnet-2023 pull request #35
Opened 2023-03-22 18:05 UTC by Hocyxa

2023-03-23 08:17 UTC, kolyanch requested changes

2023-03-23 08:17 UTC, kolyanch commented on Shop_class/Shop_class/Product.cs
> +    public int PoductGroupCode { get; set; }
*Product

2023-03-23 08:17 UTC, kolyanch commented on Shop_class/xUnitTest/ShopFixtture.cs
В имени класса и названии файла опечатка, двойная буква t

2023-03-23 08:17 UTC, kolyanch commented on Shop_class/xUnitTest/TestShop.cs
> +    /// 1) ������� �������� � ���� ������� � �������� ��������.
В файле проблемы с кодировкой

2023-03-23 08:17 UTC, kolyanch commented on Shop_class/xUnitTest/TestShop.cs
> +        var prodectinshop =
camelCase и исправить опечатку. Тут и в других тестах

2023-03-23 08:17 UTC, kolyanch commented on Shop_class/xUnitTest/TestShop.cs
> +            } into ShopSales
*shopSales

2023-03-23 09:26 UTC, Hocyxa commented on Shop_class/Shop_class/PurchaseRecord.cs
> +public class PurchaseRecord
1) В моей реализации, запись о покупке хранит колекцию продуктов, которую купил клиент, ведь клиент может приобрести множество продуктов за одну покупку.
Или лучше будет если в записи о покупке будет один продукт, и если клиент приобрёл множество продуктов, то количество записей будет равно количеству продуктво, которые клиент приобрёл?

2) Прошу прощения, возможно, не совсем понял последний абзац, вы хотите, чтобы в классе Product, описывающий продукт, была ещё коллекция покупок, и в классе Customer, описывающий клиента, была коллекция его покупок?
Из классов Customer и Product я хотел сделать таблички, к которым будут ссылать остальные классы, такие как PurchaseRecord

2023-03-23 14:03 UTC, kolyanch requested changes

2023-03-23 14:03 UTC, kolyanch commented on Shop_class/Shop_class/PurchaseRecord.cs
> +public class PurchaseRecord
Покупка характеризуется:
1. Покупателем
2. Магазином, в котором она совершена
3. Набором продуктов, которые были куплены (один продукт может быть куплен в множественном числе)
4. Датой, когда произведена покупка

Поэтому логично:
1. Класс ```ProductRecord``` считать классом для связи продукт/покупатель/магазин (тройная связь многие-ко-многим).
1. Добавить в ```PurchaseRecord``` ссылку на магазин и/или идентификатор магазина. Обратная коллекция уже еcть в ```Shop```.
2. Добавить в ```PurchaseRecord``` ссылку на продукт и/или идентификатор продукта. Коллекцию продуктов убрать.
3. Добавить в ```PurchaseRecord``` количество продукта, которое было куплено. По текущей структуре, если товар весовой, то покупатель всегда покупает весь объем продукции, имеющейся в магазине.

С точки зрения БД это будет выглядеть примерно следующим образом:
| Магазин | Покупатель | Товар | Дата | Количество |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 1  | 1  | 1 | 23.03.2023 | 1.5 |
| 1  | 1  | 2 | 23.03.2023 | 1 |
| 1  | 1  | 3 | 23.03.2023 | 3 |
| 1  | 1  | 1 | 24.03.2023 | 1 |
| 1  | 2  | 1 | 23.03.2023 | 3 |
| 1  | 2  | 2 | 23.03.2023 | 2 |
| 1  | 3  | 3 | 23.03.2023 | 1 |
| 1  | 3  | 1 | 24.03.2023 | 5.3 |

2023-03-23 14:03 UTC, kolyanch commented on Shop_class/xUnitTest/TestShop.cs
> +    private readonly ShopFixture _shopFixtture;
Тут опечатка

2023-03-26 12:43 UTC, kolyanch approved these changes

2023-03-27 16:31 UTC, closed without merging