Лабораторная работа №1, 4 вариант. Водянов Степан Денисович, 6311-100503D
itsecd/dotnet-2023 pull request #42
Opened 2023-03-26 11:49 UTC by v0dnyy

2023-03-27 05:37 UTC, kolyanch requested changes

2023-03-27 05:37 UTC, kolyanch commented on TransportMgmt/TransportMgmt.Domain/Driver.cs
> +    public string MidleName { get; set; } = string.Empty;
*Middle 
в комменте также

2023-03-27 05:37 UTC, kolyanch commented on TransportMgmt/TransportMgmt.Domain/Driver.cs
> +    public int DriverId { get; set; } = 0;
Идентификаторы во всех классах должны быть просто ```Id```

2023-03-27 05:37 UTC, kolyanch commented on TransportMgmt/TransportMgmt.Domain/Trip.cs
> +    public DateTime TimeON { get; set; } = new DateTime();
*TimeOn

2023-03-27 05:37 UTC, kolyanch commented on TransportMgmt/TransportMgmt.Domain/Trip.cs
> +    public DateTime TimeOFF { get; set; } = new DateTime();
TimeOff

2023-03-27 05:37 UTC, kolyanch commented on TransportMgmt/TransportMgmt.Tests/TransportMngmt.Tests.cs
> +        Assert.Contains(query, x => x.lastName == "�������");
Проблемы с кодировкой файла

2023-03-27 05:37 UTC, kolyanch commented on TransportMgmt/TransportMgmt.Tests/TransportMngmt.Tests.cs
> +        Assert.Equal(7, query.Count());
Использовать свойство ```Count```, а не метод

2023-03-27 05:37 UTC, kolyanch commented on TransportMgmt/TransportMgmt.Tests/TransportMngmt.Tests.cs
> +    public void InfoAboutCountTravelAvgTimeTranvelMaxTimeTravel()
В одном месте слово ```Travel``` с опечаткой

2023-03-27 05:37 UTC, kolyanch commented on TransportMgmt/TransportMgmt.Tests/TransportMngmt.Tests.cs
> +                         tripsAmount = res.Count(trip => trip.Driver.DriverId == trip.Driver.DriverId),
В данном методе и в следующем условие
```C#
trip.Driver.DriverId == trip.Driver.DriverId
```
всегда равно true

2023-03-27 15:55 UTC, v0dnyy commented
Исправил замечания. Так же пытался добавить автоматизацию с помощью github actions, но не смог исправить ошибку MSB1003

2023-03-28 04:32 UTC, kolyanch commented on TransportMgmt/TransportMgmt.Tests/TransportMngmt.Tests.cs
> +                     orderby res.Sum(query => query.TimeOff.ToBinary() - query.TimeOn.ToBinary()) descending
Тут и ниже.
Разницу между датами так не считают.
Если вы хотите найти точную разницу необходимо:
1. Найти разницу в датах:
```C#
query.TimeOff - query.TimeOn
```
Результатом будет объект типа ```TimeSpan```
2. У результата взять свойство: ```Days```, ```Minutes```, ```Seconds``` и т.д.

2023-03-28 09:36 UTC, v0dnyy commented
Исправлен алгоритм вычисления разницы между датами.

2023-03-28 10:46 UTC, kolyanch approved these changes

2023-03-28 20:07 UTC, closed without merging