Лабораторная работа №2 - Данилов Роман - 6312 - 6 вариант
itsecd/dotnet-2023 pull request #62
Opened 2023-04-10 19:11 UTC by danilovpage

2023-04-12 07:40 UTC, alxmcs requested changes

2023-04-12 07:40 UTC, alxmcs commented on lab1/Polyclinic.Domain/Polyclinic.Server/Controllers/CompletionController.cs
> +        _polyclinicRepository.Completions.Add(_mapper.Map<Completion>(completion));
Не хватает логирования - во всех остальных методах оно есть, а тут почему-то нет.

2023-04-17 08:32 UTC, alxmcs requested changes

2023-04-17 08:32 UTC, alxmcs commented on Polyclinic/Polyclinic.Server/MappingProfile.cs
> +        CreateMap<Completion, CompletionPostDto>();
Если происходит разделение Dto по методам контроллера, то оно должно происходить для всех Dao классов.
Соответственно, тут не хватает `CompletionGetDto`

2023-04-17 08:32 UTC, alxmcs commented on Polyclinic/Polyclinic.Server/MappingProfile.cs
> +        CreateMap<Registration, RegistrationPostDto>();
Аналогично - `RegistrationGetDto` нет

2023-04-18 05:03 UTC, alxmcs requested changes

2023-04-18 05:03 UTC, alxmcs commented on Polyclinic/Polyclinic.Server/MappingProfile.cs
> +        //CreateMap<Doctor, DoctorPostDto>();
Закомменченный код убрать

2023-04-18 05:03 UTC, alxmcs commented on Polyclinic/Polyclinic.Server/Dto/RegistrationGetDto.cs
> +public class RegistrationGetDto
Ты не поторопился с запросом ревью?

2023-04-18 07:18 UTC, danilovpage commented on Polyclinic/Polyclinic.Server/Dto/RegistrationGetDto.cs
> +public class RegistrationGetDto
Не понимаю, почему вижуалка не зафиксировала изменения...

2023-04-30 23:51 UTC, danilovpage commented
3 Лабораторная работа. Я так понял 2-ой пул-реквест я не смогу сделать пока этот открыт.

2023-05-02 11:16 UTC, alxmcs requested changes

2023-05-02 11:16 UTC, alxmcs commented on Polyclinic/Polyclinic.Server/Controllers/AnalyticsController.cs
> +    public async Task<IActionResult> GetInformationAboutAppointmentsPatients(DateTime lastMonth1, DateTime lastMonth2)
Не думаю, что этот метод требует параметров, временной промежуток должен высчитываться относительно `DateTime.Now`

2023-05-02 13:26 UTC, alxmcs approved these changes

2023-05-04 09:18 UTC, closed without merging