Лабораторная работа №2 - Водянов Степан 6311 - Вариант 4
itsecd/dotnet-2023 pull request #68
Opened 2023-04-11 16:57 UTC by v0dnyy

2023-04-11 18:25 UTC, kolyanch requested changes

2023-04-11 18:25 UTC, kolyanch commented on TransportMgmt/TransportMgmtServer/Controllers/DriverController.cs
> +
Лишние пустые строки удалить. Аттрибуты не отделяются от того, к чему они относятся

2023-04-11 18:25 UTC, kolyanch commented on TransportMgmt/TransportMgmtServer/Controllers/DriverController.cs
> +    /// <param name="driver"></param>
Добавить комментарии. Проверить их наличие во всех методах контроллеров

2023-04-11 18:25 UTC, kolyanch commented on TransportMgmt/TransportMgmtServer/Controllers/RequestController.cs
> +    [HttpGet("GetInfoAboutCountTravelAvgTimeTranvelMaxTimeTravel")]
Сократить этот маршрут

2023-04-11 18:25 UTC, kolyanch commented on TransportMgmt/TransportMgmtServer/Controllers/RequestController.cs
> +    public IEnumerable<DriverPropertiesRouteDto> GetInfoAboutCountTravelAvgTimeTranvelMaxTimeTravel()
*Travel

2023-04-11 18:25 UTC, kolyanch commented on TransportMgmt/TransportMgmtServer/Controllers/RequestController.cs
> +                       where (trip.tripsAmount == numOfTrips.Max(x => x.tripsAmount))
x - плохое наименование для аргумента

2023-04-11 18:25 UTC, kolyanch commented on TransportMgmt/TransportMgmtServer/Controllers/TransportController.cs
> +public class TransportController : ControllerBase
*Transport
Тут и везде ниже

2023-04-11 18:25 UTC, kolyanch commented on TransportMgmt/TransportMgmtServer/MappingProfile.cs
> +
Зачем эта пустота?

2023-04-12 06:35 UTC, v0dnyy commented on TransportMgmt/TransportMgmtServer/Controllers/TransportController.cs
> +public class TransportController : ControllerBase
а в чём ошибка?

2023-04-12 06:38 UTC, kolyanch commented on TransportMgmt/TransportMgmtServer/Controllers/TransportController.cs
> +public class TransportController : ControllerBase
Проверьте класс TransprotTypeController

2023-04-12 07:17 UTC, v0dnyy commented on TransportMgmt/TransportMgmtServer/Controllers/TransportController.cs
> +public class TransportController : ControllerBase
fixed

2023-04-12 07:24 UTC, kolyanch requested changes

2023-04-12 07:24 UTC, kolyanch commented on TransportMgmt/TransportMgmtServer/Controllers/TransprotTypeController.cs
Имя файла также необходимо исправить

2023-04-12 10:09 UTC, kolyanch approved these changes

2023-04-12 11:11 UTC, closed without merging