Лаба 1 - Фам Нгок Хунг 6312. Вариант 15
itsecd/dotnet-2023 pull request #7
Opened 2023-03-01 11:16 UTC by JirenMTA

2023-03-01 16:01 UTC, JirenMTA commented
Под скажите, пожалуйста, что надо попровить?

2023-03-02 11:45 UTC, alxmcs requested changes
Общее замечание: прогнать code cleanup по солюшену.

2023-03-02 11:45 UTC, alxmcs commented on LibrarySchool/ClassType.cs
> +public class ClassType
Данный класс должен содержать в себе коллекцию объектов типа `Student`

2023-03-02 11:45 UTC, alxmcs commented on LibrarySchool/Student.cs
> +public class Student
Данный класс должен содержать коллекцию объектов типа `Mark`

2023-03-02 11:45 UTC, alxmcs commented on LibrarySchool/Mark.cs
> +    ///
Пустая строка в саммари

2023-03-02 11:45 UTC, alxmcs commented on ServerTest/ServerTest.cs
> +    // Student ��� ���� ���� received 4, 5, 4, 5
Нарушена кодировка

2023-03-02 11:45 UTC, alxmcs commented on ServerTest/ServerTest.cs
> +    //Test for certain student reiceved all mark using LINQ
Комментарии к коду должны быть через `///`

2023-03-02 11:45 UTC, alxmcs commented on ПроектПромышПрограммирование.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ServerTest", "ServerTest\ServerTest.csproj", "{B2F0A83B-01BD-49F2-A30D-1373E04C1B2F}"
Проект с юнит-тестами лучше называть с учетом имени проекта, который в нем покрывается тестами. Поскольку там тестируется класс либа `LibrarySchool`, то логичнее было бы назвать проект с тестами `LibrarySchoolTest`

2023-03-02 11:45 UTC, alxmcs commented on ПроектПромышПрограммирование.sln
> +﻿
Называть солюшен кирилицей - не очень хорошая практика.

2023-03-02 11:45 UTC, alxmcs commented on ПроектПромышПрограммирование.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lab1", "Lab1\Lab1.csproj", "{AAE3FDD4-5E25-454C-BBB1-928B6310FFF6}"
В солюшене торчит какой-то не отслеживаемый гитом проект. От него надо избавиться.
![image](https://user-images.githubusercontent.com/70561974/222418414-43055644-0d86-436c-8663-ed023575e941.png)

2023-03-03 07:16 UTC, alxmcs commented
Если все необходимые изменения внесены, то пора запрашивать повторное ревью:
![image](https://user-images.githubusercontent.com/70561974/222656097-d5278517-23b3-4d85-aa30-1e0d91eff00f.png)

2023-03-03 07:56 UTC, alxmcs approved these changes
Код принимается

2023-03-13 07:57 UTC, closed without merging