Лабораторная работа №2 - Скобцов Владимир 6312 - Вариант 14
itsecd/dotnet-2023 pull request #71
Opened 2023-04-13 12:41 UTC by Sv163Sam

2023-04-17 09:14 UTC, alxmcs requested changes

2023-04-17 09:14 UTC, alxmcs commented on TaxiDepo.Server/Dto/RideDto.cs
> +/// <summary>
Потрясающий способ погасить варнинги об отсутствии комментов к полям и классам.
Теперь заполняй все эти щели по всему коду текстом

2023-04-18 07:02 UTC, alxmcs requested changes
Общее замечание - в репозитории лежат служебные файлы idea 
Что они тут делают и как они сюда попали - загадка, ответ на которую я не желаю знать

2023-04-19 09:31 UTC, alxmcs requested changes

2023-04-19 09:31 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +    [HttpGet("getCarDriver")]
Проглядел во время прошлых ревью - маршруты к методам должны быть апи паскаль кейсом

2023-04-19 09:31 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +    [HttpGet("userRidesAmount")]
Аналогично

2023-04-19 09:31 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +    [HttpGet("minDriversTripTime")]
Аналогично

2023-04-19 09:31 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +    [HttpGet("usersWithAmountRidesByDateRange")]
Аналогично

2023-04-19 09:31 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +            select _mapper.Map<UserDto>(obj.UserInfo)).Take(1);
Вместо того, чтобы маппить весь результат запроса, а потом брать один элемент, эффективнее было бы сделать наоборот

2023-04-19 16:29 UTC, alxmcs requested changes

2023-04-19 16:29 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +        var request = new List<string>() { $"max: {minTime}"};
а почему max

2023-04-19 16:29 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +            where (obj.TripCar == new Car(0, "A279TT163", "BMW E34", "Purple"))
и почему в запросе захардкожен автомобиль?

2023-04-19 16:29 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +            where (obj.UserInfo == new User(1, "Kotov", "Stanislav", "Pavlovich", "89290334434"))
Захардкоженный пользователь все еще на месте.
От тебя требуется 
![image](https://user-images.githubusercontent.com/70561974/233139375-08c12822-54dc-47ef-9b2c-f780278ebc08.png)
Так зачем тут в принципе нужен код с 79 строки?

2023-04-19 16:29 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +    public ActionResult<UserDto> GetUserByDateRange(DateTime date)
![image](https://user-images.githubusercontent.com/70561974/233140257-f4f9d4e1-8a17-44be-9c17-52ac98cbbd86.png)

"Указанный период" предполагает две даты

2023-04-22 09:20 UTC, alxmcs approved these changes

2023-05-02 10:58 UTC, alxmcs requested changes
Общие замечания:
* прогнать code cleanup по солюшену,
* в контроллере аналитики просто мерзотнейшие линки,
*  `.Classes` в солюшене и неймспейсах переименовать на `.Model`

2023-05-02 10:58 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +    [HttpGet("GetUsersByDate")]
Отладить linq - число поездок демонстрируется нулевым
![image](https://user-images.githubusercontent.com/70561974/235646469-683523c4-0cca-4d8b-9c27-acc1496e4647.png)
![image](https://user-images.githubusercontent.com/70561974/235646562-c721dc5d-65ae-4caa-b958-7494cf8fd95e.png)

2023-05-02 10:58 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +    [HttpGet("GetUserRides")]
Отладить linq - первые три проперти отдаются массивами с одним элементом
![image](https://user-images.githubusercontent.com/70561974/235647542-c6eaa098-10f2-4275-b30e-b79e224b1ed3.png)

2023-05-02 10:58 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +    [HttpGet("TopFiveDrivers")]
Аналогичная проблема, как и в предыдущем методе
![image](https://user-images.githubusercontent.com/70561974/235647759-1632d521-b011-44b7-8ed2-974053388dce.png)

2023-05-02 10:58 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +    public async Task<ActionResult<dynamic>> DriversTripTime()
Опять
![image](https://user-images.githubusercontent.com/70561974/235647844-af7c56f4-5026-4902-b924-755cd5360e23.png)

2023-05-02 10:58 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +    public async Task<ActionResult<dynamic>> UsesWithAmountRidesByDate(DateTime dateBefore, DateTime dateAfter)
![image](https://user-images.githubusercontent.com/70561974/235648309-db72e7a3-631b-4deb-a4b9-cdaa99c77886.png)
Опять

<img src="https://user-images.githubusercontent.com/70561974/235648447-bd513219-12aa-48a3-bea2-6a11eedbb6d7.png" height=200/>

2023-05-02 11:44 UTC, Sv163Sam commented
Добрый день, а что именно в контроллере аналитики поправить?

2023-05-02 11:45 UTC, alxmcs commented
Linq-выражения, подобности указаны в комментариях к отдельным методам

2023-05-02 14:06 UTC, alxmcs commented on TaxiDepo.Server/bin/Debug/net6.0/TaxiDepo.Server.xml
> +<?xml version="1.0"?>
Этому файлу не место в репозитории

2023-05-02 14:10 UTC, alxmcs commented on TaxiDepo.Server/Controllers/RequiredTasksController.cs
> +                    Surname =
Аналогичная проблема

2023-05-02 14:54 UTC, alxmcs approved these changes

2023-05-04 09:17 UTC, closed without merging