Стаценко Артем Николаевич, 6311-100503D - 3 Лабораторная работа, 21 вариант
itsecd/dotnet-2023 pull request #72
Opened 2023-04-14 12:47 UTC by stacenko63

2023-04-17 06:43 UTC, kolyanch requested changes
1. В модели данных явно не хватает аттрибутов для обязательных полей, ключей, индексов и прочего
2. Также предзаполнить базу данных тестовыми данными

2023-04-17 06:43 UTC, kolyanch commented on SocialNetwork/SocialNetwork.Core/SocialNetworkService.cs
> +		_groupValidator.Validate(model);
Используйте ```ValidateAsync``` тут и далее

2023-04-17 06:43 UTC, kolyanch commented on SocialNetwork/SocialNetwork.Core/SocialNetworkService.cs
> +		if (_socialNetworkRepository.GetRole(id) == null)
Тут нехватает одного слова)
Сейчас вы сравниваете Task с null. Он точно не null

2023-04-17 06:43 UTC, kolyanch commented on SocialNetwork/SocialNetwork.Data/Models/GroupDBModel.cs
> +public class GroupDBModel
Нарушение правил именования. Должно быть ```GroupDbModel```. В других классах аналогично. Файлы также переименовать

2023-04-17 06:43 UTC, kolyanch commented on SocialNetwork/SocialNetwork.Data/SocialNetworkRepository.cs
> +using System.Data;
Данный namespace используется?

2023-04-17 06:43 UTC, kolyanch commented on SocialNetwork/SocialNetwork.Data/SocialNetworkRepository.cs
> +			RoleId = adminRole.Id
adminRoler все ещё может быть null в данном случае

2023-04-17 06:43 UTC, kolyanch commented on SocialNetwork/SocialNetwork.Data/SocialNetworkRepository.cs
> +		var usersGroupsRoles = await _context.UsersGroupsRoles.ToListAsync();
Зачем данная переменная?

2023-04-17 06:43 UTC, kolyanch commented on SocialNetwork/SocialNetwork.Data/SocialNetworkRepository.cs
> +		var usersGroupsRoles = await _context.UsersGroupsRoles.ToListAsync();
Также какая-то непонятная переменная

2023-04-18 06:09 UTC, kolyanch requested changes

2023-04-18 06:09 UTC, kolyanch commented on SocialNetwork/SocialNetwork.Web/Controllers/QueryController.cs
> +		return (from user in await _socialNetworkService.GetAllUsers()
Тут ```System.NullReferenceException``` на первичном наборе данных, который указан в ```SocialNetworkContext```. Также проверить другие методы

2023-04-18 13:15 UTC, stacenko63 commented
@kolyanch Добрый вечер! Устранил все замечания

2023-04-18 15:53 UTC, kolyanch commented
Первый же запрос на Get Group:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/73119715/232833089-ad3c109d-2343-40b7-9f2b-eac8cf67a729.png">

```userId``` равен 0, хотя он должен быть 1. 
В базе также отсутствуют foreign keys

2023-04-19 11:19 UTC, stacenko63 commented
![image](https://user-images.githubusercontent.com/85314559/233059232-754c574d-71a3-4484-a41c-4cecbd517462.png)

2023-04-20 04:22 UTC, kolyanch approved these changes

2023-04-27 06:12 UTC, closed without merging