Пиженко Анастасия 6311 группа 19 вариант Лабораторная работа №1
itsecd/dotnet-2023 pull request #73
Opened 2023-04-18 09:49 UTC by PizhenkoAS

2023-04-18 09:51 UTC, PizhenkoAS commented
Написала все тесты кроме одного под номером 3 (Вывести информацию о средней стоимости препаратов каждой фармацевтической группе для каждой аптеки). Не знаю как его написать, можете, пожалуйста, подсказать?

2023-04-18 10:31 UTC, kolyanch commented
> Написала все тесты кроме одного под номером 3 (Вывести информацию о средней стоимости препаратов каждой фармацевтической группе для каждой аптеки). Не знаю как его написать, можете, пожалуйста, подсказать?

Для данного запроса вам потребуется группировка сразу по двум полям - фармгруппе и аптеке.
С точки зрения LINQ это сводится к созданию анонимного объекта.
Запрос у вас почти дописан, выглядеть должен примерно так:
```C#
var request = (
	from pharmaGroup in _fixture.PharmaGroups
	from productPharmaGroup in pharmaGroup.ProductPharmaGroup
	from productPharmacy in productPharmaGroup.Product.ProductPharmacy
	group productPharmacy by new
	{
		productPharmaGroup.PharmaGroup.PharmaGroupId,
		productPharmacy.Pharmacy.PharmacyId
	} into pharmacyGroups
	select new
	{
		PharmaGroup = pharmacyGroups.Key.PharmaGroupId,
		Pharmacy = pharmacyGroups.Key.PharmacyId,
		ProductCost = pharmacyGroups.Average(s => s.ProductCost)
	}
).ToList();
```

2023-04-18 15:35 UTC, kolyanch requested changes

2023-04-18 15:35 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Module/Group.cs
> +/// Сlass describing a group
В слове Class первая буква кириллическая, сделайте во всех классах латинскую, чтобы дальше проблем не было

2023-04-18 15:35 UTC, kolyanch commented on LICENSE
Лицензию не нужно удалять

2023-04-18 15:35 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Module/Group.cs
> +    public int GroupId { get; set; } = 0;
Идентификаторы именовать просто ```Id```

2023-04-18 15:35 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Module/Group.cs
> +    public List<Product> Product { get; set; } = new List<Product>();
Тут наверное ```Products```. Аналогично в других классах - именуйте списки во множественном числе

2023-04-18 15:35 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Module/Pharmacy.cs
> +    public Pharmacy(string pharmancyName, string pharmancyPhone, string pharmancyAddress, string pharmancyDirector)
4 раза опечатка в слове ```pharmacy```

2023-04-18 15:35 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Module/Pharmacy.cs
> +        PharmacyDirector = pharmancyName;
Тут опечатка в имени аргумента

2023-04-18 15:35 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Test/PharmacyCityNetworkFixture.cs
> +﻿namespace PharmacyCityNetwork.Tests;
Неверное пространство имен

2023-04-18 15:35 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Test/PharmacyCityNetworkTests.cs
> +namespace PharmacyCityNetwork.Module;
Неверное пространство имен

2023-04-18 15:35 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Test/PharmacyCityNetworkTests.cs
> +                       && (String.Compare(pharmacy.PharmacyAddress, "S")) > 0
Может тут проще использовать метод ```pharmacy.PharmacyAddress.Contains```

2023-04-18 15:35 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Test/PharmacyCityNetworkTests.cs
> +    public void PharmacyFromAdress()
*Address

2023-04-19 04:14 UTC, kolyanch requested changes

2023-04-19 04:14 UTC, kolyanch commented on LICENSE
> +Copyright (c) 2023 ������� �����
Проблема с кодировкой

2023-04-19 04:14 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Module/Group.cs
> +    public int GroupId { get; set; } = 0;
```GroupId``` необходимо переименовать в ```Id``` и так во всех классах

2023-04-19 04:14 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetwork.Test/PharmacyCityNetworkFixture.cs
> +﻿namespace PharmacyCityNetwork.Tests;
namespace должен соответствовать имени проекта + путь к файлу. В данном случае: ```PharmacyCityNetwork.Test```

2023-04-19 05:47 UTC, kolyanch approved these changes

2023-04-25 04:33 UTC, kolyanch requested changes

2023-04-25 04:33 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetworkServer/Controllers/AnalyticsController.cs
> +    /// <returns></returns>
Отсутствуют комментарии для параметров методов контроллеров. Проверить во всех контроллерах

2023-04-25 04:33 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetworkServer/Controllers/GroupController.cs
> +            _logger.LogInformation($"Not found group: {id}");
Избавиться от интерполирования строк в логах. Тут и проверить в других методах

2023-04-25 04:33 UTC, kolyanch commented on PharmacyCityNetwork/PharmacyCityNetworkServer/Dto/GroupGetDto.cs
> +    public int Id { get; set; } = 0;
Свойства типа int не имеет смысла инициализировать нулем. Это значение по умолчанию. Тут и в других DTO

2023-04-25 09:44 UTC, kolyanch approved these changes

2023-04-27 06:13 UTC, closed without merging