LAB3_Вариант 11_Нгуен Ван Зуе
itsecd/dotnet-2023 pull request #77
Opened 2023-04-22 20:16 UTC by nguyenvandue-vn

2023-04-27 09:29 UTC, alxmcs requested changes

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/BicycleController.cs
> +            return Ok(_mapper.Map<BicycleGetDto>(bicycle));
Нет логирования успешного выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/BicycleController.cs
> +        return Ok();
Нет логирования выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/BicycleController.cs
> +            return Ok();
Нет логирования успешного выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/BicycleController.cs
> +            return Ok();
Нет логирования успешного выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/BicycleTypeController.cs
> +            return Ok(bicycleType);
Нет логирования успешного выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/CustomerController.cs
> +            return Ok(_mapper.Map<CustomerGetDto>(customer));
Нет логирования успешного выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/CustomerController.cs
> +        return Ok();
Нет логирования выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/CustomerController.cs
> +            return Ok();
Нет логирования успешного выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/CustomerController.cs
> +            return Ok();
Нет логирования успешного выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RentalController.cs
> +            return Ok(_mapper.Map<RentalGetDto>(rental));
Нет логирования успешного выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RentalController.cs
> +        return Ok();
Нет логирования выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RentalController.cs
> +            return Ok();
Нет логирования успешного выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RentalController.cs
> +            return Ok();
Нет логирования успешного выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +        return await (from bicycle in context.Bicycles
Нет логирования выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +        return await (from customer in context.Customers.Include(c => c.Rentals)
Нет логирования выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +        await using var context = await _contextFactory.CreateDbContextAsync();
Нет логирования выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +        await using var context = await _contextFactory.CreateDbContextAsync();
Нет логирования выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +        await using var context = await _contextFactory.CreateDbContextAsync();
Нет логирования выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +        await using var context = await _contextFactory.CreateDbContextAsync();
Нет логирования выполнения

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/Dto/BicycleGetDto.cs
> +    public List<BicycleRental> Rentals { get; set; } = new List<BicycleRental>();
Коллекция Dao типа в Dto

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/Dto/CustomerGetDto.cs
> +    public List<BicycleRental> Rentals { get; set; } = new List<BicycleRental>();
Коллекция Dao типа в Dto

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/BicycleController.cs
> +        return _mapper.Map<IEnumerable<BicycleGetDto>>(context.Bicycles);
![image](https://user-images.githubusercontent.com/70561974/234817214-94cde17f-b2a5-443b-ba1e-133f556c8bfe.png)
![image](https://user-images.githubusercontent.com/70561974/234817325-2e2f840f-53e6-4f19-a58d-8cb997e049fb.png)

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Domain/BicycleType.cs
> +public class BicycleType
У класса отсутствует Dto

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/BicycleTypeController.cs
> +        return await context.BicycleTypes.ToListAsync();
Аналогичная проблема: 
![image](https://user-images.githubusercontent.com/70561974/234818164-bebb17d2-15d6-4a44-87ca-c1f5e998e1c4.png)
![image](https://user-images.githubusercontent.com/70561974/234818291-47fccf1c-1d23-4ca9-a35c-e9f689cbd313.png)
Аналогичная ситуация в целом происходит с выводом всех связанных сущностей, стоит посмотреть на свои Dto

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +    public async Task<IEnumerable> GetCustomersWithMostRentals()
![image](https://user-images.githubusercontent.com/70561974/234820144-559fca82-4000-489d-b906-50db18f1a5f0.png)

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +    public async Task<IEnumerable> GetTotalRentalTimePerBicycleType()
![image](https://user-images.githubusercontent.com/70561974/234820461-00bc6a16-c6f1-4405-a823-16ff0523d955.png)

2023-04-27 09:29 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +    public async Task<IEnumerable> MinMaxAvgRentalTime()
![image](https://user-images.githubusercontent.com/70561974/234821061-068a5ce9-cc18-4804-ab7e-480f5b99ba5a.png)

2023-05-02 10:24 UTC, alxmcs requested changes

2023-05-02 10:24 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +    /// Returns a list of all clients who rented mountain bicycles, sort by name..
Лишняя точка в конце предложения

2023-05-02 10:24 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +    public async Task<IActionResult> GetTotalRentalTimePerBicycleType()
Ошибка в linq выражении все еще не побеждена
![image](https://user-images.githubusercontent.com/70561974/235641951-cbdf91b9-4c05-4d28-b184-4ac694d7a405.png)

2023-05-02 10:24 UTC, alxmcs commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +    public async Task<IActionResult> MinMaxAvgRentalTime()
Аналогично:
![image](https://user-images.githubusercontent.com/70561974/235642299-c2fdb4e4-573f-4f7f-a0d5-c5b6c06a134c.png)

2023-05-03 09:26 UTC, nguyenvandue-vn commented on BicycleRentals.Server/ControllersModels/RequestsController.cs
> +    public async Task<IActionResult> MinMaxAvgRentalTime()
Я все готов

2023-05-03 12:07 UTC, alxmcs approved these changes

2023-05-17 09:22 UTC, closed without merging